---
- name: Remove Whoopsie
  ansible.builtin.apt:
    name: whoopsie
    state: absent
    purge: true
  become: true

- name: Remove all unused packages
  ansible.builtin.apt:
    autoremove: true
    purge: true
  become: true

- name: Prevent future installations of Whoopsie
  ansible.builtin.copy:
    src: no-whoopsie
    dest: /etc/apt/preferences.d/no-whoopsie
    owner: root
    group: root
    mode: "0644"
  notify: apt update
  become: true

- name: Flush the handlers
  ansible.builtin.meta: flush_handlers
