---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install VLC
  ansible.builtin.apt:
    name: vlc
    state: present
  become: true
