---
- name: Prepare
  hosts: all
  tasks:
    - name: Update the repository cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Install the missing packages
      ansible.builtin.apt:
        pkg:
          - dirmngr
          - gpg-agent
        state: present
      become: true
