---
- name: Set up the workstation
  hosts: all
  roles:
    - debloat_ubuntu

    - setup

    - flatpak

    - configure_gnome

    - role: zsh
      zsh_default_shell: true

    - oh_my_zsh

    - powerlevel10k

    - guake

    - role: nvm
      nvm_node_versions:
        - { version: 20 }
        - { version: 22, default: true }

    - role: sdkman
      sdkman_java_versions:
        - { version: 17 }
        - { version: 21, default: true }

    - maven

    - docker

    - google_chrome

    - firefox

    - keepassxc

    - solaar

    - vlc

    - signal

    - gitkraken

    - postman

    - discord

    - slack

    - cleanup
