---
- name: Set up the workstation
  hosts: all
  roles:
    # Prepare
    - debloat_ubuntu
    - prepare

    # Package managers
    - flatpak

    # Desktop environment
    - configure_gnome

    # Terminal
    - role: zsh
      zsh_default_shell: true

    - oh_my_zsh

    - powerlevel10k

    - guake

    # Development tools
    - role: sdkman
      sdkman_java_versions:
        - { version: 17 }
        - { version: 21, default: true }

    - maven

    - role: nvm
      nvm_node_versions:
        - { version: 20 }
        - { version: 22, default: true }

    - docker

    - vagrant

    - jetbrains_toolbox

    - gitkraken

    - postman

    # Virtualization tools
    - libvirt
    - virt_manager

    # Applications
    - google_chrome

    - firefox

    - keepassxc

    - solaar

    - vlc

    - pinta

    - color_picker

    - signal

    - slack

    - discord

    # Clean up
    - cleanup
