---
- name: Development tools
  hosts: all
  roles:
    - role: zsh
      zsh_default_shell: true

    - role: oh_my_zsh

    - role: powerlevel10k

    - role: java
      java_version: 21

    - role: maven
