---
- name: Install cURL
  ansible.builtin.dnf:
    name: curl
    state: present
  become: true

- name: Install Git
  ansible.builtin.dnf:
    name: git
    state: present
  become: true

- name: Check Oh My Zsh installation directory
  ansible.builtin.stat:
    path: "~/.oh-my-zsh"
  register: oh_my_zsh_install_dir

- name: Install Oh My Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not oh_my_zsh_install_dir.stat.exists
  changed_when: true
