---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install the dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gpg
    state: present
  become: true

- name: Create the APT keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Download the HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.asc
    owner: root
    group: root
    mode: "0644"
    checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029
  become: true

- name: Dearmor the HashiCorp GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor --output /etc/apt/keyrings/hashicorp.gpg /tmp/hashicorp.asc
    creates: /etc/apt/keyrings/hashicorp.gpg
  become: true

- name: Add the HashiCorp repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp
    update_cache: true
    state: present
  become: true

- name: Install Packer
  ansible.builtin.apt:
    name: packer
    state: present
  become: true
