---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install Maven
  ansible.builtin.apt:
    name: maven
    state: present
  become: true
