---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install Flatpak
  ansible.builtin.apt:
    name: flatpak
    state: present
  become: true

- name: Add the Flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
  become: true

- name: Install GNOME Software
  ansible.builtin.apt:
    name: gnome-software
    state: present
  become: true

- name: Install the GNOME Software Flatpak plugin
  ansible.builtin.apt:
    name: gnome-software-plugin-flatpak
    state: present
  become: true
