---
- name: Install Zsh
  ansible.builtin.dnf:
    name: zsh
    state: present
  become: true

- name: Get the Zsh installation path
  ansible.builtin.command: which zsh
  register: zsh_install_path
  changed_when: false

- name: Set Zsh as the default shell
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    shell: '{{ zsh_install_path.stdout }}'
  become: true
  when: zsh_default_shell
