---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install Zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true

- name: Set Zsh as the default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
  when: zsh_default_shell
