---
- name: Verify
  hosts: all
  tasks:
    - name: Check that Zsh is installed
      ansible.builtin.command: zsh --version
      changed_when: false

    - name: Get the default shell
      ansible.builtin.shell: |
        set -o pipefail
        getent passwd root | awk -F: '{print $7}'
      register: default_shell
      changed_when: false

    - name: Check that Zsh is the default shell
      ansible.builtin.assert:
        that:
          - default_shell.stdout == '/bin/zsh'
        success_msg: Zsh is the default shell
        fail_msg: Zsh is not the default shell
