---
- name: Verify
  hosts: all
  tasks:
    - name: Check that Zsh is installed
      ansible.builtin.command: zsh --version
      changed_when: false

    - name: Get the Zsh installation path
      ansible.builtin.command: which zsh
      register: zsh_install_path
      changed_when: false

    - name: Check that Zsh is the default shell
      ansible.builtin.assert:
        that:
          - ansible_user_shell == zsh_install_path.stdout
        success_msg: Zsh is the default shell
        fail_msg: Zsh is not the default shell
