---
- name: Prepare
  hosts: all
  tasks:
    - name: Update the repository cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    # See https://github.com/geerlingguy/docker-ubuntu1804-ansible/issues/6
    - name: Install the missing packages
      ansible.builtin.apt:
        name:
          - dirmngr
          - gpg-agent
          - ubuntu-pro-client
        state: present
      become: true

    # See https://github.com/debuerreotype/debuerreotype/issues/10
    - name: Create the missing man directories
      ansible.builtin.file:
        path: /usr/share/man/man{{ item }}
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: true
      loop: '{{ range(1, 9) | list }}'
