---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Download the Eclipse Adoptium GPG key
  ansible.builtin.get_url:
    url: https://packages.adoptium.net/artifactory/api/gpg/key/public
    dest: /etc/apt/trusted.gpg.d/adoptium.asc
    checksum: sha256:a46d5d3ab75c3c86dddf1bfd2957a067a24b1c6b2d2ed2bc69294bf970c5160b
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Add the Eclipse Adoptium repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.adoptium.net/artifactory/deb {{ ansible_distribution_release }} main"
    filename: adoptium
    update_cache: true
    state: present
  become: true

# See https://github.com/debuerreotype/debuerreotype/issues/10
- name: Create missing man directory if not exists
  ansible.builtin.file:
    path: /usr/share/man/man1
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install JDK {{ java_version }}
  ansible.builtin.apt:
    name: temurin-{{ java_version }}-jdk
    state: present
  become: true
