---
- name: Enable the minimize and maximize buttons in the titlebar
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"
    state: present
