---
- name: Download adw-gtk3
  ansible.builtin.get_url:
    # Using v5.3 because newer versions require GTK v4.16+ (and Ubuntu Desktop 24.04 uses GTK v4.14)
    url: https://github.com/lassekongo83/adw-gtk3/releases/download/v5.3/adw-gtk3v5.3.tar.xz
    dest: /tmp/adw-gtk3.tar.xz
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Extract adw-gtk3
  ansible.builtin.unarchive:
    src: /tmp/adw-gtk3.tar.xz
    dest: /usr/share/themes/
    remote_src: true
  become: true

- name: Set the GTK theme for legacy applications to "adw-gtk3-dark"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'adw-gtk3-dark'"
    state: present
