---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Get the list of installed packages
  ansible.builtin.package_facts:
    manager: apt

- name: Install GNOME Tweaks
  ansible.builtin.apt:
    name: gnome-tweaks
    state: present
  become: true

- name: Install GNOME Extension Manager
  ansible.builtin.apt:
    name: gnome-shell-extension-manager
    state: present
  become: true

- name: Install GNOME Firmware
  ansible.builtin.apt:
    name: gnome-firmware
    state: present
  become: true

- name: Install GNOME Software
  ansible.builtin.apt:
    name: gnome-software
    state: present
  become: true

- name: Install GNOME Software Flatpak plugin
  ansible.builtin.apt:
    name: gnome-software-plugin-flatpak
    state: present
  when: "'flatpak' in ansible_facts.packages"
  become: true
