---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install psutil
  ansible.builtin.apt:
    name: python3-psutil # Required to use the Ansible "community.general.dconf" module
    state: present
  become: true
