---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install GNOME Tweaks
  ansible.builtin.apt:
    name: gnome-tweaks
    state: present
  become: true

- name: Install GNOME Extension Manager
  ansible.builtin.apt:
    name: gnome-shell-extension-manager
    state: present
  become: true
