---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install the dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gpg
    state: present
  become: true

- name: Create the APT keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Download the Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.asc
    owner: root
    group: root
    mode: "0644"
    checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570
  become: true

- name: Dearmor the Docker GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor --output /etc/apt/keyrings/docker.gpg /tmp/docker.asc
    creates: /etc/apt/keyrings/docker.gpg
  become: true

- name: Add the Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    update_cache: true
    state: present
  become: true

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Add the user to the Docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups: docker
  become: true
