---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install the dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gpg
    state: present
  become: true

- name: Create the APT keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Disable the default Google Chrome config (provided by Ubuntu)
  ansible.builtin.copy:
    dest: /etc/default/google-chrome
    content: |
      repo_add_once="false"
      repo_reenable_on_distupgrade="false"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Download the Google GPG key
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /tmp/google.asc
    owner: root
    group: root
    mode: "0644"
    checksum: sha256:0acccf28849439e3b2f7c60f899da45186a3a9b2fd02cc88cd44b25200016c56
  become: true

- name: Dearmor the Google GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor --output /etc/apt/keyrings/google.gpg /tmp/google.asc
    creates: /etc/apt/keyrings/google.gpg
  become: true

- name: Add the Google Chrome repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google.gpg] https://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    update_cache: true
    state: present
  become: true

- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
  become: true
